version: "2"

run:
  timeout: 5m

linters:
  default: standard # errcheck, govet, ineffassign, staticcheck, unused
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
    - usestdlibvars
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintln
        - fmt.Fprintf
        - fmt.Fprint
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/mmoehabb/maestro
