ALTER TABLE tasks ADD COLUMN pr_head_sha TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN merge_sha TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN reopen_sha TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN pr_base TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN cleanup_pending INTEGER NOT NULL DEFAULT 0;
